baseURL = 'https://dimparar.github.io/thecybersecurityblog/'
languageCode = 'en-us'
title = 'The Cyber Security Blog'
theme = 'PaperMod'

enableEmoji = true

[menus]
[[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    identifier = 'blog'
    name = 'Blog'
    pageRef = '/blog/'
    weight = 20
[[menus.main]]
    identifier = 'tags'
    name = 'Tags'
    pageRef = '/tags/'
    weight = 30
[[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/About/'
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    dateFormat = "02 Jan 2006"
